<?php
$clg_list=
array("A V S Engineering College ",
"A.R.J. College of Engineering and Technology ",
"A.S.L. Pauls College of Engineering and Technology ",
"A.V.C. College of Engineering ",
"Adithya Institute of Technology ",
"Akshaya College of Engineering & Technology ",
"Al-Ameen Engineering College ",
"Angel College of Engineering and Technology ",
"Anjalai Ammal Mahalingam Engineering College ",
"Annai College of Engineering and Technology ",
"Annai Mathammal Sheela Engineering College ",
"Annapoorana Engineering College ",
"Arasu Engineering College ",
"As-Salam College of Engineering and Technology ",
"Bharathiyar Institute of Engineering for Women ",
"C M S College of Engineering and Technology ",
"Chettinad College of Engineering and Technology ",
"Christ The King Engineering College ",
"CMS College of Engineering ",
"Coimbatore Institute of Engineering and Technology ",
"Coimbatore Institute of Technology ",
"CSI College of Engineering ",
"Dhanalakshmi Srinivasan College of Engineering ",
"Dhanalakshmi Srinivasan Engineering College ",
"Dr. Mahalingam College of Engineering & Technology ",
"Dr. N G P Institute of Technology ",
"Dr. Nagarathinamâ€™s College of Engineering ",
"Dr. Nallini Institute of Engineering and Technology ",
"E.G.S. Pillay Engineering College ",
"Easa College of Engineering and Technology ",
"Erode Builder Educational Trustâ€™s Group of Institutions ",
"Erode Sengunthar Engineering College ",
"Excel College of Engineering and Technology ",
"Excel College of Engineering for Women ",
"Excel Engineering College ",
"Gnanamani College of Engineering ",
"Gnanamani College of Technology ",
"Government College of Engineering â€“ Salem ",
"Government College of Technology, Coimbatore ",
"Greentech College of Engineering for Women ",
"Hindusthan College of Engineering and Technology ",
"Hindusthan Institute of Technology ",
"Indus College of Engineering ",
"INFO Institute of Engineering ",
"Institute of Road and Transport Technology ",
"J C T College of Engineering and Technology ",
"J K K Munirajah College of Technology ",
"J.K.K. Nataraja College of Engineering and Technology ",
"Jansons Institute of Technology ",
"Jay Shriram Group of Institutions ",
"K P R Institute of Engineering and Technology ",
"K.K.C College of Engineering and Technology ",
"K.S.K. College of Engineering and Technology ",
"K.S.R. College of Engineering ",
"K.S.Rangasamy College of Technology (Autyonomous) ",
"Kalaignar Karunanidhi Institute of Technology ",
"Kalaivani College of Technology ",
"Karpagam College of Engineering (Autonomous) ",
"Karpagam Institute of Technology ",
"Karur College of Engineering ",
"Kathir College of Engineering ",
"KGISL Institute of Technology ",
"King College of Technology ",
"KTVR Knowledge Park for Engineering and Technology ",
"M. Kumarasamy College of Engineering ",
"M.P. Nachimuthu M. Jaganathan Engineering College ",
"Maharaja Engineering College ",
"Maharaja Engineering College for Women ",
"Maharaja Institute of Technology ",
"Maharaja Prithvi Engineering College ",
"Mahendra College of Engineering ",
"Mahendra Engineering College ",
"Mahendra Engineering College for Women ",
"Mahendra Institute of Engineering and Technology ",
"Mahendra Institute of Technology ",
"Meenakshi Ramaswamy Engineering College ",
"Muthayammal Engineering College ",
"Nandha College of Technology ",
"Nandha Engineering College ",
"Narasuâ€™s Sarathy Institute of Technology ",
"Nehru Institute of Engineering and Technology ",
"Nehru Institute of Technology ",
"P A College of Engineering and Technology ",
"P G P College of Engineering and Technology ",
"P.R. Engineering College ",
"Paavaai Group of Institutions ",
"Paavai College of Engineering ",
"Paavai Engineering College ",
"Parisutham Institute of Technology and Science ",
"Park College of Engineering and Technology ",
"Park College of Technology ",
"Pavai College of Technology ",
"Ponnaiyah Ramajayam College of Engineering and Technology ",
"PPG Institute of Technology ",
"Professional Educational Trustâ€™s Group of Institutions ",
"R V S College of Engineering and Technology ",
"Ranganathan Engineering College ",
"Roever College of Engineering and Technology ",
"Roever Engineering College ",
"RVS Technical Campus - Coimbatore ",
"S N S College of Engineering ",
"S R S College of Engineering and Technology ",
"S V S College of Engineering ",
"Salem College of Engineering and Technology ",
"Sasurie Academy of Engineering ",
"Sasurie College of Engineering ",
"Selvam College of Technology ",
"Sembodai Rukmani Varatharajan Engineering College ",
"Sengunthar College of Engineering ",
"Sengunthar Engineering College ",
"Shree Venkateshwara Hi-tech Engineering College ",
"Sir Issac Newton College of Engineering and Technology ",
"SMR East Coast College of Engineering and Technology ",
"SNS College of Technology ",
"Sona College of Technology ",
"Sree Sakthi Engineering College ",
"SRG Engineering College ",
"Sri Eshwar College of Engineering ",
"Sri Krishna College of Engineering & Technology (Autonomous) ",
"Sri Krishna College of Technology ",
"Sri Ramakrishna Engineering College (Autonomous) ",
"Sri Ramakrishna Institute of Technology ",
"Sri Ramanathan Engineering College ",
"Sri Shakthi Institute of Engineering and Technology ",
"Sriguru Institute of Technology ",
"Srinivasan Engineering College ",
"St. Josephâ€™s College of Engineering and Technology ",
"Star Lion College of Engineering and Technology ",
"Surya Engineering College ",
"Tagore Institute of Engineering and Technology ",
"Tamilnadu College of Engineering ",
"Tejaa Shakthi Institute of Technology for Women ",
"The Kavery College of Engineering ",
"The Kavery Engineering College ",
"United Institute of Technology ",
"V K S College of Engineering and Technology ",
"V S A Educational and Charitable Trustâ€™s Group of Institutions ",
"V.S.B. Engineering College ",
"Vandayar Engineering College ",
"Velalar College of Engineering and Technology ",
"Vidyaa Vikas College of Engineering and Technology ",
"Vivekanandha College of Engineering for Women ",
"Vivekanandha College of Technology for women ",
"Vivekanandha Engineering College for Women ",
"Vivekanandha Institute of Engineering & Technology for Women ");
$user="tnslpp";
$pass="sKxquzEt";
$host="localhost";
$db_name="tnslpp";
$table_name="basic_det";
?>